name: CI

on:
  push:
    branches:
      - dev
      - main
    tags:
  pull_request:
  release:

jobs:
  check-copyright:
    name: Copyright
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: License header
        run: .scripts/check-copyright-notice.sh
      - name: Authors
        run: .scripts/check-notice-authors.sh origin/main

  lint:
    name: GolangCI-Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check vanity import
        run: .scripts/check-vanity-imports.sh $GITHUB_WORKSPACE
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Unit Tests
        run: go test -timeout 60s ./...

  race-tests:
    name: Race Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-race
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Unit Race Tests
        run: go test -timeout 120s -race ./...
